GET https://localhost:7247/api/Forms/GetForms HTTP/1.1
###
GET https://localhost:7247/api/Forms/GetForm/2 HTTP/1.1
###
POST https://localhost:7247/api/Forms/PostForm HTTP/1.1
content-type: application/json

{
    "name": "Maciek",
    "topic": "Przykładowy temat",
    "email": "Jakiś tam e-mail",
    "message": "Taka o! wiadomość",
    "ip": "192.168.0.1"
}

###
POST https://localhost:7247/api/Forms/PostForm HTTP/1.1
content-type: application/json

{
    "name": "Daria",
    "topic": "Teamt grafiki",
    "email": "E-mail Wspólniczki",
    "message": "Nowe wieści",
    "ip": "192.168.0.2"
}

###
POST https://localhost:7247/api/Forms/PostForm HTTP/1.1
content-type: application/json

{
    "name": "Kalcia",
    "topic": "Co do zrobienia?",
    "email": "E-mail ode Kalci",
    "message": "Komplementy",
    "ip": "192.168.0.3"
}

###
PUT https://localhost:7247/api/Forms/PutForm/2 HTTP/1.1
content-type: application/json

{
    "id": "3",
    "name": "Uszek",
    "topic": "Uszek zwany Mateuszek!",
    "email": "E-mail Uszka",
    "message": "Umówić się na piwo",
    "ip": "192.168.0.4"
}

###
DELETE https://localhost:7247/api/Forms/DeleteForm/1 HTTP/1.1